// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VoiceRecogEvalServer.Models;

namespace VoiceRecogEvalServer.Migrations
{
    [DbContext(typeof(RecordingDatabaseContext))]
    partial class RecordingDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("VoiceRecogEvalServer.Models.VoiceRecording", b =>
                {
                    b.Property<int>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasUserError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedVoiceLine")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SoundFile")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UploadedUtcTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordingId");

                    b.ToTable("Recordings");
                });
#pragma warning restore 612, 618
        }
    }
}
